apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/GoogleCloudPlatform/microservices-demo/v0.8.0/release/kubernetes-manifests.yaml
  #- otel-alias.yaml

patches:
  - target:
      version: v1
      kind: Service
      name: frontend-external
    patch: |-
      - op: replace
        path: /spec/type
        value: ClusterIP
  - target:
      kind: Deployment
      name: "^(frontend|cartservice|checkoutservice|currencyservice|emailservice|paymentservice|productcatalogservice|recommendationservice|shippingservice|adservice|loadgenerator)$"
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otel-collector.observability.svc.cluster.local:4317"